import "./globals.css";

import { Inter } from "next/font/google";
import ClientLayout from './client-layout';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
});


export const metadata = {
  title: "CPFED",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
        <body>
            <ClientLayout>
                {children}
            </ClientLayout>
        </body>
    </html>
  );
}
